# Generated by Django 2.2.2 on 2019-06-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='distance',
            field=models.IntegerField(),
        ),
    ]
