# Generated by Django 2.2.2 on 2019-06-29 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190628_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='speed',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='distance',
            field=models.IntegerField(help_text='Вводить данные в метрах'),
        ),
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.IntegerField(help_text='Ввидить данные в минутах'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 29, 12, 21, 4, 221711, tzinfo=utc), null=True),
        ),
    ]
