# Generated by Django 2.2.2 on 2019-06-29 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190629_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 29, 12, 23, 39, 33992, tzinfo=utc), null=True),
        ),
    ]
