# Generated by Django 2.2.2 on 2019-06-29 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190629_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 29, 12, 24, 29, 671539, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
