# Generated by Django 2.2.2 on 2019-07-03 15:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_auto_20190629_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 3, 15, 1, 22, 145964, tzinfo=utc), null=True)),
                ('distance', models.IntegerField(help_text='Enter data in meters')),
                ('duration', models.IntegerField(help_text='Enter data in minutes')),
                ('speed', models.FloatField(default=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
